version: '3.7'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8888:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpresspassword
    volumes:
      - ./:/var/www/html  # Мапуємо локальну папку ./wordpress до /var/www/html у контейнері

  db:
    image: mysql:8.0
    user: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpresspassword
    volumes:
      - ./database:/var/lib/mysql  # Мапуємо локальну папку ./mysql до /var/lib/mysql у контейнері

volumes:
  wordpress_data:
  db_data:
